/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserdetailRouteImport } from './routes/userdetail'
import { Route as EdituserRouteImport } from './routes/edituser'
import { Route as AdduserRouteImport } from './routes/adduser'
import { Route as IndexRouteImport } from './routes/index'

const UserdetailRoute = UserdetailRouteImport.update({
  id: '/userdetail',
  path: '/userdetail',
  getParentRoute: () => rootRouteImport,
} as any)
const EdituserRoute = EdituserRouteImport.update({
  id: '/edituser',
  path: '/edituser',
  getParentRoute: () => rootRouteImport,
} as any)
const AdduserRoute = AdduserRouteImport.update({
  id: '/adduser',
  path: '/adduser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adduser': typeof AdduserRoute
  '/edituser': typeof EdituserRoute
  '/userdetail': typeof UserdetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adduser': typeof AdduserRoute
  '/edituser': typeof EdituserRoute
  '/userdetail': typeof UserdetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adduser': typeof AdduserRoute
  '/edituser': typeof EdituserRoute
  '/userdetail': typeof UserdetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adduser' | '/edituser' | '/userdetail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adduser' | '/edituser' | '/userdetail'
  id: '__root__' | '/' | '/adduser' | '/edituser' | '/userdetail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdduserRoute: typeof AdduserRoute
  EdituserRoute: typeof EdituserRoute
  UserdetailRoute: typeof UserdetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userdetail': {
      id: '/userdetail'
      path: '/userdetail'
      fullPath: '/userdetail'
      preLoaderRoute: typeof UserdetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edituser': {
      id: '/edituser'
      path: '/edituser'
      fullPath: '/edituser'
      preLoaderRoute: typeof EdituserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adduser': {
      id: '/adduser'
      path: '/adduser'
      fullPath: '/adduser'
      preLoaderRoute: typeof AdduserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdduserRoute: AdduserRoute,
  EdituserRoute: EdituserRoute,
  UserdetailRoute: UserdetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
